/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppDashboardChart {
    }
    interface AppFeedback {
    }
    interface AppFirstDashboard {
    }
    interface AppHome {
    }
    interface AppModule {
    }
    interface AppProfile {
        "name": string;
    }
    interface AppRoot {
    }
    interface AppUser {
    }
    interface AppViewDashboard {
    }
    interface PageHelp {
        "headline": string;
        "messages": any[];
    }
    interface PageModal {
    }
}
declare global {
    interface HTMLAppDashboardChartElement extends Components.AppDashboardChart, HTMLStencilElement {
    }
    var HTMLAppDashboardChartElement: {
        prototype: HTMLAppDashboardChartElement;
        new (): HTMLAppDashboardChartElement;
    };
    interface HTMLAppFeedbackElement extends Components.AppFeedback, HTMLStencilElement {
    }
    var HTMLAppFeedbackElement: {
        prototype: HTMLAppFeedbackElement;
        new (): HTMLAppFeedbackElement;
    };
    interface HTMLAppFirstDashboardElement extends Components.AppFirstDashboard, HTMLStencilElement {
    }
    var HTMLAppFirstDashboardElement: {
        prototype: HTMLAppFirstDashboardElement;
        new (): HTMLAppFirstDashboardElement;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppModuleElement extends Components.AppModule, HTMLStencilElement {
    }
    var HTMLAppModuleElement: {
        prototype: HTMLAppModuleElement;
        new (): HTMLAppModuleElement;
    };
    interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {
    }
    var HTMLAppProfileElement: {
        prototype: HTMLAppProfileElement;
        new (): HTMLAppProfileElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAppUserElement extends Components.AppUser, HTMLStencilElement {
    }
    var HTMLAppUserElement: {
        prototype: HTMLAppUserElement;
        new (): HTMLAppUserElement;
    };
    interface HTMLAppViewDashboardElement extends Components.AppViewDashboard, HTMLStencilElement {
    }
    var HTMLAppViewDashboardElement: {
        prototype: HTMLAppViewDashboardElement;
        new (): HTMLAppViewDashboardElement;
    };
    interface HTMLPageHelpElement extends Components.PageHelp, HTMLStencilElement {
    }
    var HTMLPageHelpElement: {
        prototype: HTMLPageHelpElement;
        new (): HTMLPageHelpElement;
    };
    interface HTMLPageModalElement extends Components.PageModal, HTMLStencilElement {
    }
    var HTMLPageModalElement: {
        prototype: HTMLPageModalElement;
        new (): HTMLPageModalElement;
    };
    interface HTMLElementTagNameMap {
        "app-dashboard-chart": HTMLAppDashboardChartElement;
        "app-feedback": HTMLAppFeedbackElement;
        "app-first-dashboard": HTMLAppFirstDashboardElement;
        "app-home": HTMLAppHomeElement;
        "app-module": HTMLAppModuleElement;
        "app-profile": HTMLAppProfileElement;
        "app-root": HTMLAppRootElement;
        "app-user": HTMLAppUserElement;
        "app-view-dashboard": HTMLAppViewDashboardElement;
        "page-help": HTMLPageHelpElement;
        "page-modal": HTMLPageModalElement;
    }
}
declare namespace LocalJSX {
    interface AppDashboardChart {
    }
    interface AppFeedback {
    }
    interface AppFirstDashboard {
    }
    interface AppHome {
    }
    interface AppModule {
    }
    interface AppProfile {
        "name"?: string;
    }
    interface AppRoot {
    }
    interface AppUser {
    }
    interface AppViewDashboard {
    }
    interface PageHelp {
        "headline"?: string;
        "messages"?: any[];
    }
    interface PageModal {
    }
    interface IntrinsicElements {
        "app-dashboard-chart": AppDashboardChart;
        "app-feedback": AppFeedback;
        "app-first-dashboard": AppFirstDashboard;
        "app-home": AppHome;
        "app-module": AppModule;
        "app-profile": AppProfile;
        "app-root": AppRoot;
        "app-user": AppUser;
        "app-view-dashboard": AppViewDashboard;
        "page-help": PageHelp;
        "page-modal": PageModal;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-dashboard-chart": LocalJSX.AppDashboardChart & JSXBase.HTMLAttributes<HTMLAppDashboardChartElement>;
            "app-feedback": LocalJSX.AppFeedback & JSXBase.HTMLAttributes<HTMLAppFeedbackElement>;
            "app-first-dashboard": LocalJSX.AppFirstDashboard & JSXBase.HTMLAttributes<HTMLAppFirstDashboardElement>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-module": LocalJSX.AppModule & JSXBase.HTMLAttributes<HTMLAppModuleElement>;
            "app-profile": LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "app-user": LocalJSX.AppUser & JSXBase.HTMLAttributes<HTMLAppUserElement>;
            "app-view-dashboard": LocalJSX.AppViewDashboard & JSXBase.HTMLAttributes<HTMLAppViewDashboardElement>;
            "page-help": LocalJSX.PageHelp & JSXBase.HTMLAttributes<HTMLPageHelpElement>;
            "page-modal": LocalJSX.PageModal & JSXBase.HTMLAttributes<HTMLPageModalElement>;
        }
    }
}
